// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0rtlty3mxcsHNO6G0-L_2NFk2-uvWRVk',
    appId: '1:125960494947:web:0c244d17cbe405901dbd56',
    messagingSenderId: '125960494947',
    projectId: 'fir-notifications-76391',
    authDomain: 'fir-notifications-76391.firebaseapp.com',
    storageBucket: 'fir-notifications-76391.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpMTSZG07H8zsjKYjKklgTlA0Ax_XiyPg',
    appId: '1:125960494947:android:6c3a026c51983c271dbd56',
    messagingSenderId: '125960494947',
    projectId: 'fir-notifications-76391',
    storageBucket: 'fir-notifications-76391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZYr4y1WSchUvK35PQOZqU-HOplEVX1A',
    appId: '1:125960494947:ios:b22de5560001297d1dbd56',
    messagingSenderId: '125960494947',
    projectId: 'fir-notifications-76391',
    storageBucket: 'fir-notifications-76391.appspot.com',
    iosBundleId: 'com.example.firebasenotifications.firebaseNotificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbZYr4y1WSchUvK35PQOZqU-HOplEVX1A',
    appId: '1:125960494947:ios:b22de5560001297d1dbd56',
    messagingSenderId: '125960494947',
    projectId: 'fir-notifications-76391',
    storageBucket: 'fir-notifications-76391.appspot.com',
    iosBundleId: 'com.example.firebasenotifications.firebaseNotificationsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0rtlty3mxcsHNO6G0-L_2NFk2-uvWRVk',
    appId: '1:125960494947:web:0efa79c168e09ba31dbd56',
    messagingSenderId: '125960494947',
    projectId: 'fir-notifications-76391',
    authDomain: 'fir-notifications-76391.firebaseapp.com',
    storageBucket: 'fir-notifications-76391.appspot.com',
  );
}
